# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170811_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='cell',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='resume',
            name='experiance',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
