# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-23 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170923_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='experiance',
            new_name='PG',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='hobbies',
            new_name='UG',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='qualification',
            new_name='expone',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
        migrations.AddField(
            model_name='resume',
            name='exptwo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resume',
            name='image',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='obj',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='resume',
            name='school',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
