# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-23 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170923_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='expfrom',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='resume',
            name='expto',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
