# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-23 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20170923_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='expfrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='expto',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
