# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-23 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20170923_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='address1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
