# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-23 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20170923_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
